trigger:
  branches:
    include:
    - main
  paths:
    include:
    - landingZones/tf/**
    - landingZones/tf/pipelines/platformlz-deployment-pipelines.yaml

pool: 'selfhosted'

stages:
- stage: sub_deploy
  displayName: sub_deploy
  jobs:
  - job: sub_deploy
    displayName: sub_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-plz-sub-wi-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          # deploy on mg scope
          $response = (
             new-AzManagementGroupDeploymentStack `
                -Name "platform-sub-stack" `
                -ManagementGroupId "plbtf-platform" `
                -Location "West India" `
                -TemplateParameterFile "$(System.DefaultWorkingDirectory)/landingZones/tf/params/platform/nonprod.bicepparam" `
                -ActionOnUnManage 'DeleteAll' `
                -DenySettingsMode 'None' `
                -Force
                )
                # -ActionOnUnManage 'DetachAll' ` # | DeleteResources | DeleteAll
                # -DenySettingsMode 'None' ` # | DenyDelete | DenyWriteAndDelete `
                
          write-output '------- Outputs -------'
          $subscriptionId = $response.Outputs.subscriptionId.Value
          write-output 'subscriptionId: ' $subscriptionId
          echo "##vso[task.setvariable variable=subscriptionId;isoutput=true]$subscriptionId"

          write-output '------- Response -------'
          $response

        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      name: 'sub_deploy'
      displayName: 'sub_deploy'

- stage: tag_policy
  displayName: tag_policy
  jobs:
  - job: tag_policy
    displayName: tag_policy
    variables:
      - name: subscriptionId
        value: $[ stageDependencies.sub_deploy.sub_deploy.outputs['sub_deploy.subscriptionId'] ]
    steps: 
    - task: azurepowershell@5
      inputs:
        azuresubscription: 'mi-platform-plz-sub-wi-nonprod-001'
        scripttype: 'inlinescript' # 'filepath'
        #scriptpath: '/script.ps1'
        inline: |
          write-output '------- Input Variables -------'
          write-output 'subscriptionId: ' $(subscriptionId)

          Set-AzContext -Subscription $(subscriptionId)

          # deploy on sub scope
          $response = (
             New-AzSubscriptionDeploymentStack `
                -Name "tag-policy-stack" `
                -Location "West India" `
                -TemplateParameterFile "$(System.DefaultWorkingDirectory)/landingZones/tf/params/platform/policy-nonprod.bicepparam" `
                -ActionOnUnManage 'DeleteAll' `
                -DenySettingsMode 'DenyDelete' `
                -Force
                )
                # -ActionOnUnManage 'DetachAll' ` # | DeleteResources | DeleteAll
                # -DenySettingsMode 'None' ` # | DenyDelete | DenyWriteAndDelete `
                
          write-output '------- Response -------'
          $response

        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      name: 'tag_policy'
      displayName: 'tag_policy'
