trigger:
  branches:
    include:
    - main
  paths:
    include:
    - landingZones/tf/params/**

pool: 'selfhosted'

stages:
- stage: sub_deploy
  displayName: sub_deploy
  jobs:
  - job: sub_deploy
    displayName: sub_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-plz-sub-wi-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "platform-sub-stack" -ManagementGroupId "plbtf-platform" -Location "West India" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/landingZones/tf/params/platform/nonprod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'sub deploy'
