trigger:
  branches:
    include:
    - main
  paths:
    include:
    - management-groups/bicep/**

pool: 'selfhosted'

stages:
- stage: dev_mg
  displayName: 
  jobs:
  - job: dev_mg
    displayName: dev_mg
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "dev-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/dev.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'whatif_dev_mg'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "dev-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/dev.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'deploy_dev_mg'

- stage: test_mg
  displayName: 
  jobs:
  - job: test_mg
    displayName: test_mg
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "test-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/test.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force -WhatIf
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'whatif_test_mg'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "test-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/test.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'deploy_test_mg'

- stage: nonprod_mg
  displayName: 
  jobs:
  - job: nonprod_mg
    displayName: nonprod_mg
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "nonprod-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/nonprod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force -WhatIf
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'whatif_nonprod_mg'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "nonprod-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/nonprod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'deploy_nonprod_mg'

- stage: prod_mg
  displayName: 
  jobs:
  - job: prod_mg
    displayName: prod_mg
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "prod-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/prod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force -WhatIf
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'whatif_prod_mg'
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "prod-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/management-groups/bicep/params/prod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'deploy_prod_mg'
