trigger:
  branches:
    include:
    - main

pool: 'selfhosted'

stages:
- stage: dev_mg_deploy
  displayName: 
  jobs:
  - job: dev_mg_deploy
    displayName: dev_mg_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          Write-Host "Deploying Dev Management Group Deployment Stack"
          new-AzManagementGroupDeploymentStack -Name "dev-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/bicep/infra/mgmtGroupStructure/params/dev.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Deploy MG Structure to Dev'

- stage: test_mg_deploy
  displayName: 
  jobs:
  - job: test_mg_deploy
    displayName: test_mg_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          Write-Host "Deploying Test Management Group Deployment Stack"
          new-AzManagementGroupDeploymentStack -Name "test-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/bicep/infra/mgmtGroupStructure/params/test.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Deploy MG Structure to Test'

- stage: nonprod_mg_deploy
  displayName: 
  jobs:
  - job: nonprod_mg_deploy
    displayName: nonprod_mg_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          Write-Host "Deploying NonProd Management Group Deployment Stack"
          new-AzManagementGroupDeploymentStack -Name "nonprod-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/bicep/infra/mgmtGroupStructure/params/nonprod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Deploy MG Structure to NonProd'

- stage: prod_mg_deploy
  displayName: 
  jobs:
  - job: prod_mg_deploy
    displayName: prod_mg_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-mg-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          Write-Host "Deploying Prod Management Group Deployment Stack"
          new-AzManagementGroupDeploymentStack -Name "prod-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/bicep/infra/mgmtGroupStructure/params/prod.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Deploy MG Structure to Prod'
