trigger:
  branches:
    include:
    - main

pool: 'selfhosted'

stages:
  - stage: stage_name
    displayName: some name
    jobs:
    - job: Job
      displayName: some job name
      steps:
      - script: echo "Hello World"
        displayName: "Print Hello World"
