trigger:
  branches:
    include:
    - main
  paths:
    include:
    - bicep/infra/landingZones/params/**

pool: 'selfhosted'

stages:
- stage: sub_deploy
  displayName: sub_deploy
  jobs:
  - job: sub_deploy
    displayName: sub_deploy
    steps: 
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'mi-platform-standard-sub-sc-nonprod-001'
        ScriptType: 'InlineScript' # 'FilePath'
        #ScriptPath: '/script.ps1'
        Inline: |
          new-AzManagementGroupDeploymentStack -Name "dev-mg-stack" -ManagementGroupId "c0f414ff-9e2d-4011-929c-fe21ed71b218" -Location "Sweden Central" -TemplateParameterFile "$(System.DefaultWorkingDirectory)/bicep/infra/mgmtGroupStructure/params/dev.bicepparam" -ActionOnUnManage 'DeleteAll' -DenySettingsMode 'none' -Force
        #ScriptArguments: '-param1 value1 -param2 value2'
        errorActionPreference: 'stop' # 'continue' | 'silentlyContinue'
        FailOnStandardError: false
        azurePowerShellVersion:  'LatestVersion' # 'OtherVersion'
        #preferredAzurePowerShellVersion: '7.1.0'
        pwsh: true
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'deploy sub'
